server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://api-gateway:8080;
        proxy_set_header Host $host; # this takes real host and set it 
        proxy_set_header X-Real-IP $remote_addr; # thats the real ip addtr and store 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # it list where it had been before this server
        proxy_set_header X-Forwarded-Proto $scheme; #checking https o no fr further security 

        proxy_http_version 1.1;
        proxy_buffering off; # no waiting rule 
    }
}
