Include /etc/nginx/modsec/modsecurity.conf    #like the brain like libarary
SecRuleEngine On # if off thats default and that will just log not blocking
SecDefaultAction "phase:1,deny,status:403" #if u see bad guy kick him out with 403 error 
SecDefaultAction "phase:2,deny,status:403"
SecRequestBodyLimit 10485760 #thats limimt of how much data a user can upload
SecRequestBodyNoFiles Off #
SecResponseBodyLimit 524288
SecPcreMatchLimit 1000 #if u read confusing stuff and in loop , this breaks u from it 
SecPcreMatchLimitRecursion 1000

Include /etc/nginx/owasp-modsecurity-crs/crs-setup.conf # this  give all tricks bad guys use pretect from common attack
Include /etc/nginx/owasp-modsecurity-crs/rules/*.conf

# ADD: Hardening for the Friend Search feature
# This blocks IPs that try to "guess" usernames too rapidly
SecAction "id:900001,phase:1,nolog,pass,initcol:ip=%{REMOTE_ADDR}"
SecRule REQUEST_URI "@contains /api/users/search" \
    "id:900002,phase:2,pause,deny,status:429,setvar:ip.search_count=+1,expirevar:ip.search_count=60" \
    "chain"
SecRule IP:SEARCH_COUNT "@gt 20" ""#   





