services:
  auth-service:
    build: ../backend/auth-service
    expose:
      - "8000"

  user-service:
    build: ../backend/user-service
    expose:
      - "8001"

  diary-service:
    build: ../backend/diary-service
    expose:
      - "8002"

  waf:
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: security_waf
    ports:
      - "8081:80"
    volumes:
      - ../backend/waf/config/modsecurity-hardened.conf:/etc/nginx/modsec/modsecurity-hardened.conf:ro
      - ../backend/waf/config/default.conf:/etc/nginx/templates/conf.d/default.conf.template:ro
    environment:
      - BACKEND=http://api-gateway:8080
      - PARANOIA=1
    networks:
      - external
      - internal
    depends_on:
      - api-gateway

  realtime-service:
    build: ../backend/realtime-service
    expose:
      - "8003"

  api-gateway:
    build: ../backend/api-gateway
    expose:
      - "8080"
    depends_on:
      - auth-service
      - user-service
      - diary-service
      - realtime-service
    networks:
      - internal

  vault:
    image: hashicorp/vault:1.15
    container_name: security_vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=my-secret-token
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    networks:
      - internal


networks:
  external:
  internal:
